---
image_resource:
  type: docker-image
  source:
    repository: cfgarden/grootfs-ci

platform: linux

inputs:
  - name: grootfs-release-develop
  - name: grootfs-release-master

outputs:
  - name: release-merged

run:
  path: grootfs-release-develop/ci/scripts/merge-master-into-develop.sh
